// server/controllers/meetingController.js
const { google } = require('googleapis');
const oauth2Client = require('../utils/googleClient');
const { generateMeetingPrep } = require('../utils/agent');
const transporter = require('../utils/emailTransporter');
const User = require('../models/User');

exports.getMeetings = async (req, res) => {
  try {
    const { email } = req.query; 

    if (!email) {
      console.log("⚠️ No email provided in request");
      return res.json([]); 
    }

    const user = await User.findOne({ where: { email } });

    if (!user || !user.refreshToken) {
      console.log("⚠️ User not found or no Refresh Token");
      return res.json([]); 
    }

    oauth2Client.setCredentials({
      refresh_token: user.refreshToken
    });

    const calendar = google.calendar({ version: 'v3', auth: oauth2Client });
    
    const now = new Date();
    const nextWeek = new Date();
    nextWeek.setDate(now.getDate() + 7);

    const response = await calendar.events.list({
      calendarId: 'primary',
      timeMin: now.toISOString(),
      timeMax: nextWeek.toISOString(),
      maxResults: 10,
      singleEvents: true,
      orderBy: 'startTime',
    });

    const meetings = response.data.items.map(event => ({
      id: event.id,
      title: event.summary,
      startTime: event.start.dateTime || event.start.date,
      description: event.description
    }));

    res.json(meetings);

  } catch (error) {
    console.error('Calendar Fetch Error:', error.message);
    res.json([]); 
  }
};

exports.analyzeMeeting = async (req, res) => {
  try {
    const { title } = req.body;
    
    if (!title) {
      return res.status(400).json({ error: 'Meeting title is required' });
    }

    console.log(`🤖 Analyzing meeting: ${title}`);
    const report = await generateMeetingPrep(title);
    
    res.json(report);
  } catch (error) {
    console.error('Analysis Error:', error.message);
    res.status(500).json({ error: 'Failed to analyze meeting' });
  }
};

exports.sendEmail = async (req, res) => {
  try {
    const { email, report } = req.body;

    if (!email || !report) {
      return res.status(400).json({ error: 'Email and report are required' });
    }

    const emailHTML = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h1 style="color: #2563eb;">Meeting Brief: ${report.prospectName}</h1>
        <p><strong>Company:</strong> ${report.company}</p>
        <p><strong>Role:</strong> ${report.role}</p>
        
        <h2 style="color: #ef4444;">🔥 Pain Points</h2>
        <ul>
          ${report.painPoints?.map(p => `
            <li>
              <strong>${p.title}</strong><br/>
              ${p.detail}
            </li>
          `).join('') || ''}
        </ul>
        
        <h2 style="color: #22c55e;">💡 Talking Points</h2>
        <ul>
          ${report.talkingPoints?.map(t => `
            <li>
              <strong>${t.title}</strong><br/>
              ${t.detail}
            </li>
          `).join('') || ''}
        </ul>
        
        <h2>Tips</h2>
        <ul>
          ${report.tips?.map(tip => `<li>${tip}</li>`).join('') || ''}
        </ul>
        
        <hr/>
        <p style="color: #9ca3af; font-size: 12px;">Generated by Anapan AI Sales Agent</p>
      </div>
    `;

    await transporter.sendMail({
      from: process.env.EMAIL_USER,
      to: email,
      subject: `Meeting Brief: ${report.prospectName} @ ${report.company}`,
      html: emailHTML,
    });

    console.log(`✅ Email sent to ${email}`);
    res.json({ success: true, message: 'Email sent successfully' });
  } catch (error) {
    console.error('Email Error:', error.message);
    res.status(500).json({ error: 'Failed to send email' });
  }
};