const { google } = require('googleapis');
const oauth2Client = require('../utils/googleClient');
const { generateMeetingPrep } = require('../utils/agent'); // AI Agent Import
const transporter = require('../utils/emailTransporter'); // Email Import

// 1. Get Meetings
exports.getMeetings = async (req, res) => {
  try {
    const calendar = google.calendar({ version: 'v3', auth: oauth2Client });
    const now = new Date();
    const nextWeek = new Date();
    nextWeek.setDate(now.getDate() + 7);

    const response = await calendar.events.list({
      calendarId: 'primary',
      timeMin: now.toISOString(),
      timeMax: nextWeek.toISOString(),
      maxResults: 10,
      singleEvents: true,
      orderBy: 'startTime',
    });

    const meetings = response.data.items.map(event => ({
      id: event.id,
      title: event.summary,
      startTime: event.start.dateTime || event.start.date,
      description: event.description
    }));

    res.json(meetings);
  } catch (error) {
    console.error('Calendar Fetch Error:', error);
    // Agar auth fail ho (token expire), toh empty array bhejo taki app crash na ho
    res.json([]); 
  }
};

// 2. Analyze Meeting (AI)
exports.analyzeMeeting = async (req, res) => {
  const { title } = req.body;
  if (!title) return res.status(400).send("Title required");

  try {
    const report = await generateMeetingPrep(title);
    res.json(report);
  } catch (error) {
    console.error("AI Analysis Failed:", error);
    res.status(500).json({ error: "Analysis failed" });
  }
};

// 3. Send Email
exports.sendEmail = async (req, res) => {
  const { email, report } = req.body;
  if (!email || !report) return res.status(400).json({ error: "Missing data" });

  try {
    // HTML Template Logic (Simple version)
    const htmlContent = `
      <h2>Meeting Prep for ${report.prospectName}</h2>
      <p><strong>Role:</strong> ${report.role} @ ${report.company}</p>
      <h3>Pain Points:</h3>
      <ul>${report.painPoints.map(p => `<li><b>${p.title}:</b> ${p.detail}</li>`).join('')}</ul>
      <p>Generated by Anapan AI</p>
    `;

    await transporter.sendMail({
        from: process.env.EMAIL_USER,
        to: email,
        subject: `🎯 Prep: ${report.prospectName}`,
        html: htmlContent
    });
    
    res.json({ success: true });
  } catch (error) {
    console.error("Email Error:", error);
    res.status(500).json({ error: error.message });
  }
};